name: Build latest and update README

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: Generate latest build
        id: build
        run: |
          npm install
          npm run build
          npm run verison
          git add .
          git commit -am "chore: update build"
          git push -u origin ${{ github.ref_name }}
